"""
auto_config.py

Automated Device Profiler & Initial Setup Wizard for MachineMake Device Server.

Analyzes the hardware map generated by HardwareMapper (OS, architecture,
I2C devices, interfaces, battery) to infer the most likely device type:
  - Windows / PC with Battery -> Laptop
  - Windows / Linux PC without Battery -> Desktop Computer / Server
  - Raspberry Pi / Linux SBC with PCA9685 (0x40) & MPU6050 (0x68) -> Quadruped Robot
  - Raspberry Pi / Linux SBC with PCA9685 only -> Robotic Arm
  - Raspberry Pi with camera & no servos -> Vision / Camera Node
  - Microcontroller / ESP32 / Generic SBC -> MachineMake Node

Also provides an interactive terminal wizard for initial onboarding.
"""

import logging
import os
import platform
import socket
import sys
from typing import Any, Dict, List, Optional

logger = logging.getLogger("auto_config")

# Pre-defined device profiles matching MachineMake app templates
PROFILES = {
    "quadruped": {
        "title": "Quadruped Robot (4-Legged Walking Dog)",
        "type": "robot",
        "description": "16-channel PCA9685 servo driver with inverse kinematics & MPU6050 IMU",
        "default_name": "MachineMake Quadruped Dog",
        "configuration": {
            "pca9685": {"bus": 1, "address": "0x40"},
            "servos": {
                "front_left_shoulder": {"controller": "pca9685", "channel": 0},
                "front_left_upper": {"controller": "pca9685", "channel": 1},
                "front_right_shoulder": {"controller": "pca9685", "channel": 2},
                "front_right_upper": {"controller": "pca9685", "channel": 3},
                "rear_left_shoulder": {"controller": "pca9685", "channel": 4},
                "rear_left_upper": {"controller": "pca9685", "channel": 5},
                "rear_right_shoulder": {"controller": "pca9685", "channel": 6},
                "rear_right_upper": {"controller": "pca9685", "channel": 7},
            },
            "imu": {"bus": 1, "address": "0x68"},
            "led": {"gpio_pin": 10},
        },
        "safety_limits": {
            "max_walk_distance_m": 5.0,
            "max_turn_angle_deg": 180.0,
        },
    },
    "robotic_arm": {
        "title": "Robotic Arm (Multi-DOF Manipulator)",
        "type": "robot",
        "description": "Multi-axis servo manipulator powered by PCA9685",
        "default_name": "MachineMake Robotic Arm",
        "configuration": {
            "pca9685": {"bus": 1, "address": "0x40"},
            "servos": {
                "base_rotation": {"controller": "pca9685", "channel": 0},
                "shoulder": {"controller": "pca9685", "channel": 1},
                "elbow": {"controller": "pca9685", "channel": 2},
                "wrist_pitch": {"controller": "pca9685", "channel": 3},
                "gripper": {"controller": "pca9685", "channel": 4},
            },
        },
        "safety_limits": {
            "max_reach_m": 1.0,
        },
    },
    "laptop": {
        "title": "Laptop / Portable Computer",
        "type": "computer",
        "description": "Personal laptop workstation with battery and network interfaces",
        "default_name": f"{socket.gethostname()} Laptop",
        "configuration": {
            "display": True,
            "portable": True,
        },
        "safety_limits": {},
    },
    "computer": {
        "title": "Desktop PC / Server / Workstation",
        "type": "computer",
        "description": "Stationary PC or server workstation",
        "default_name": f"{socket.gethostname()} PC",
        "configuration": {
            "display": True,
            "portable": False,
        },
        "safety_limits": {},
    },
    "camera_node": {
        "title": "Smart Vision / Camera Node",
        "type": "camera",
        "description": "Standalone camera / monitoring device with video stream capabilities",
        "default_name": f"{socket.gethostname()} Camera",
        "configuration": {
            "camera": {"stream_port": 8554, "resolution": "1280x720"},
        },
        "safety_limits": {},
    },
    "microcontroller": {
        "title": "Microcontroller / Generic SBC Node",
        "type": "device",
        "description": "Generic I/O node with GPIO, PWM, and I2C controls",
        "default_name": "MachineMake Node",
        "configuration": {},
        "safety_limits": {},
    },
}


def _has_battery() -> bool:
    """Detects whether a battery sensor is present (indicating a laptop or portable device)."""
    try:
        import psutil
        battery = psutil.sensors_battery()
        return battery is not None
    except Exception:
        return False


def infer_profile_from_hardware(hardware_map: Dict[str, Any]) -> str:
    """Heuristic rule engine to detect the most appropriate profile from hardware_map."""
    device_info = hardware_map.get("device", {})
    os_name = (device_info.get("os") or platform.system()).lower()
    platform_name = (device_info.get("platform") or "").lower()
    interfaces = hardware_map.get("interfaces", {})
    devices = hardware_map.get("devices", {})

    # 1. Check I2C buses for connected robotics chips
    detected_chips = set()
    for bus in devices.get("i2c", []):
        for dev in bus.get("devices", []):
            addr = dev.get("address", "").lower()
            candidates = dev.get("candidates", [])
            if addr == "0x40" or "PCA9685" in candidates:
                detected_chips.add("PCA9685")
            if addr == "0x68" or "MPU6050" in candidates:
                detected_chips.add("MPU6050")

    # If PCA9685 and/or MPU6050 are detected on a Raspberry Pi / Linux SBC
    if "PCA9685" in detected_chips and "MPU6050" in detected_chips:
        return "quadruped"
    if "PCA9685" in detected_chips:
        return "robotic_arm"

    # If Raspberry Pi platform or Linux SBC
    if "raspberry" in platform_name or (os_name == "linux" and interfaces.get("gpio")):
        # If camera is detected without servos
        if devices.get("cameras"):
            return "camera_node"
        return "quadruped"  # Default robot profile for Pi projects

    # 2. Check PC / Workstation / Laptop (Windows, macOS, Linux PC)
    if os_name in ("windows", "darwin") or platform_name == "pc" or platform.machine().lower() in ("x86_64", "amd64"):
        if _has_battery():
            return "laptop"
        return "computer"

    # 3. Fallback
    return "microcontroller"


def build_config_for_profile(profile_key: str, custom_name: Optional[str] = None) -> Dict[str, Any]:
    """Builds a complete device_config.json dictionary from a profile key."""
    template = PROFILES.get(profile_key, PROFILES["quadruped"])
    name = custom_name or template["default_name"]

    return {
        "identity": {
            "name": name,
            "profile": profile_key,
            "type": template["type"],
        },
        "configuration": dict(template.get("configuration", {})),
        "safety_limits": dict(template.get("safety_limits", {})),
        "connection_loss_policy": {
            "interactive_control": "safe_stop",
            "autonomous_tasks": "continue",
        },
    }


def run_setup_wizard(
    hardware_map: Dict[str, Any],
    interactive: bool = True,
    save_path: Optional[str] = None,
) -> Dict[str, Any]:
    """Runs the setup wizard. Prompts the user if interactive, otherwise applies best inference."""
    inferred_key = infer_profile_from_hardware(hardware_map)
    chosen_key = inferred_key
    chosen_name = None

    is_interactive = interactive and sys.stdin.isatty()

    if is_interactive:
        dev = hardware_map.get("device", {})
        sys_info = hardware_map.get("system", {})
        os_str = (dev.get("os") or platform.system()).capitalize()
        arch_str = dev.get("architecture") or platform.machine()
        battery_detected = _has_battery()

        print("\n" + "=" * 68)
        print("  MACHINE MAKE — AUTOMATED DEVICE DETECTION & SETUP WIZARD")
        print("=" * 68)
        print("  Detected Hardware:")
        print(f"    - Operating System: {os_str} ({arch_str})")
        print(f"    - Platform:         {dev.get('platform', 'Standard PC')}")
        print(f"    - CPU Cores:        {sys_info.get('cpu', {}).get('cores', 'N/A')}")
        print(f"    - Battery Sensor:   {'Present (Portable Device)' if battery_detected else 'None (Mains / Stationary)'}")
        print(f"    - Suggested Type:   {PROFILES[inferred_key]['title']} (Recommended)")
        print("-" * 68)
        print("  Select the device profile to configure:")

        profile_keys = list(PROFILES.keys())
        default_index = profile_keys.index(inferred_key) + 1

        for i, key in enumerate(profile_keys, start=1):
            marker = " (Recommended)" if key == inferred_key else ""
            print(f"    [{i}] {PROFILES[key]['title']}{marker}")

        try:
            choice_str = input(f"\nEnter choice [1-{len(profile_keys)}], default [{default_index}]: ").strip()
            if choice_str:
                idx = int(choice_str) - 1
                if 0 <= idx < len(profile_keys):
                    chosen_key = profile_keys[idx]
        except (ValueError, EOFError, KeyboardInterrupt):
            print("\nDefaulting to recommended profile.")
            chosen_key = inferred_key

        default_name = PROFILES[chosen_key]["default_name"]
        try:
            name_input = input(f"Enter device name (default: '{default_name}'): ").strip()
            if name_input:
                chosen_name = name_input
        except (EOFError, KeyboardInterrupt):
            pass

    config_dict = build_config_for_profile(chosen_key, custom_name=chosen_name)

    if save_path:
        import json
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        with open(save_path, "w") as f:
            json.dump(config_dict, f, indent=2)
        if is_interactive:
            print(f"\nConfiguration successfully saved to: {save_path}")
            print("=" * 68 + "\n")

    return config_dict
